using System.Text.Json;
using System.Text.Json.Serialization;
using Chaos.Common.Collections;
using Chaos.Common.Definitions;
using Chaos.Data;
using Chaos.Definitions;
using Chaos.Geometry.Abstractions;
using Chaos.Schemas.Aisling;
using Chaos.Schemas.Content;
using Chaos.Schemas.Data;
using Chaos.Schemas.MetaData;
using Chaos.Schemas.Templates;

// ReSharper disable ArrangeAttributes

namespace Chaos.Serialization;

[JsonSerializable(typeof(AislingSchema))]
[JsonSerializable(typeof(ItemRequirementSchema))]
[JsonSerializable(typeof(LearningRequirementsSchema))]
[JsonSerializable(typeof(LootDropSchema))]
[JsonSerializable(typeof(ShardingOptionsSchema))]
[JsonSerializable(typeof(LootTableSchema))]
[JsonSerializable(typeof(MerchantSpawnSchema))]
[JsonSerializable(typeof(MetafileSchema))]
[JsonSerializable(typeof(MonsterSpawnSchema))]
[JsonSerializable(typeof(ReactorTileSchema))]
[JsonSerializable(typeof(StaticReactorTileSchema))]
[JsonSerializable(typeof(WorldMapNodeSchema))]
[JsonSerializable(typeof(WorldMapSchema))]
[JsonSerializable(typeof(DialogTemplateSchema))]
[JsonSerializable(typeof(ItemTemplateSchema))]
[JsonSerializable(typeof(MapTemplateSchema))]
[JsonSerializable(typeof(MerchantTemplateSchema))]
[JsonSerializable(typeof(MonsterTemplateSchema))]
[JsonSerializable(typeof(ReactorTileTemplateSchema))]
[JsonSerializable(typeof(SkillTemplateSchema))]
[JsonSerializable(typeof(SpellTemplateSchema))]
[JsonSerializable(typeof(DialogOptionSchema))]
[JsonSerializable(typeof(AttributesSchema))]
[JsonSerializable(typeof(BankSchema))]
[JsonSerializable(typeof(EffectsBarSchema))]
[JsonSerializable(typeof(EffectSchema))]
[JsonSerializable(typeof(EquipmentSchema))]
[JsonSerializable(typeof(InventorySchema))]
[JsonSerializable(typeof(ItemSchema))]
[JsonSerializable(typeof(LegendMarkSchema))]
[JsonSerializable(typeof(LegendSchema))]
[JsonSerializable(typeof(MapInstanceSchema))]
[JsonSerializable(typeof(SkillBookSchema))]
[JsonSerializable(typeof(SkillSchema))]
[JsonSerializable(typeof(SpellBookSchema))]
[JsonSerializable(typeof(SpellSchema))]
[JsonSerializable(typeof(StatSheetSchema))]
[JsonSerializable(typeof(StatsSchema))]
[JsonSerializable(typeof(TimedEventCollectionSchema))]
[JsonSerializable(typeof(TimedEventSchema))]
[JsonSerializable(typeof(UserOptionsSchema))]
[JsonSerializable(typeof(UserStatSheetSchema))]
[JsonSerializable(typeof(EnumCollection))]
[JsonSerializable(typeof(FlagCollection))]
[JsonSerializable(typeof(EventMetaSchema))]
[JsonSerializable(typeof(MundaneIllustrationMetaSchema))]
[JsonSerializable(typeof(List<ItemSchema>))]
[JsonSerializable(typeof(List<SkillSchema>))]
[JsonSerializable(typeof(List<SpellSchema>))]
[JsonSerializable(typeof(List<EffectSchema>))]
[JsonSerializable(typeof(List<LegendMarkSchema>))]
[JsonSerializable(typeof(List<TimedEventSchema>))]
[JsonSerializable(typeof(List<MonsterSpawnSchema>))]
[JsonSerializable(typeof(List<MerchantSpawnSchema>))]
[JsonSerializable(typeof(List<StaticReactorTileSchema>))]
[JsonSerializable(typeof(List<EventMetaSchema>))]
[JsonSerializable(typeof(List<MundaneIllustrationMetaSchema>))]
[JsonSerializable(typeof(ICollection<ItemSchema>))]
[JsonSerializable(typeof(ICollection<SkillSchema>))]
[JsonSerializable(typeof(ICollection<SpellSchema>))]
[JsonSerializable(typeof(ICollection<EffectSchema>))]
[JsonSerializable(typeof(ICollection<LegendMarkSchema>))]
[JsonSerializable(typeof(ICollection<TimedEventSchema>))]
[JsonSerializable(typeof(ICollection<MonsterSpawnSchema>))]
[JsonSerializable(typeof(ICollection<MerchantSpawnSchema>))]
[JsonSerializable(typeof(ICollection<StaticReactorTileSchema>))]
[JsonSerializable(typeof(ICollection<EventMetaSchema>))]
[JsonSerializable(typeof(ICollection<MundaneIllustrationMetaSchema>))]
[JsonSerializable(typeof(IEnumerable<ItemSchema>))]
[JsonSerializable(typeof(IEnumerable<SkillSchema>))]
[JsonSerializable(typeof(IEnumerable<SpellSchema>))]
[JsonSerializable(typeof(IEnumerable<EffectSchema>))]
[JsonSerializable(typeof(IEnumerable<LegendMarkSchema>))]
[JsonSerializable(typeof(IEnumerable<TimedEventSchema>))]
[JsonSerializable(typeof(IEnumerable<MonsterSpawnSchema>))]
[JsonSerializable(typeof(IEnumerable<MerchantSpawnSchema>))]
[JsonSerializable(typeof(IEnumerable<StaticReactorTileSchema>))]
[JsonSerializable(typeof(IEnumerable<EventMetaSchema>))]
[JsonSerializable(typeof(IEnumerable<MundaneIllustrationMetaSchema>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(HashSet<string>))]
[JsonSerializable(typeof(Animation))]
[JsonSerializable(typeof(IPoint))]
[JsonSerializable(typeof(ILocation))]
[JsonSerializable(typeof(Stat))]
[JsonSerializable(typeof(BodyAnimation))]
[JsonSerializable(typeof(AoeShape))]
[JsonSerializable(typeof(TargetFilter))]
[JsonSerializable(typeof(EquipmentType))]
[JsonSerializable(typeof(Stat?))]
[JsonSerializable(typeof(BodyAnimation?))]
[JsonSerializable(typeof(AoeShape?))]
[JsonSerializable(typeof(TargetFilter?))]
[JsonSerializable(typeof(EquipmentType?))]
[JsonSerializable(typeof(LevelCircle))]
[JsonSerializable(typeof(byte))]
[JsonSerializable(typeof(sbyte))]
[JsonSerializable(typeof(short))]
[JsonSerializable(typeof(ushort))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(uint))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(ulong))]
[JsonSerializable(typeof(decimal))]
[JsonSerializable(typeof(float))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(byte?))]
[JsonSerializable(typeof(sbyte?))]
[JsonSerializable(typeof(short?))]
[JsonSerializable(typeof(ushort?))]
[JsonSerializable(typeof(int?))]
[JsonSerializable(typeof(uint?))]
[JsonSerializable(typeof(long?))]
[JsonSerializable(typeof(ulong?))]
[JsonSerializable(typeof(decimal?))]
[JsonSerializable(typeof(float?))]
[JsonSerializable(typeof(double?))]
public partial class SerializationContext : JsonSerializerContext { }